name: K6 Load Testing Pipeline

on:
  push:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run K6 test in Grafana Cloud
        uses: grafana/k6-action@v0.2.0
        with:
          filename: k6-script.js
          cloud: true
        env:
          run: ${{ secrets.K6_CLOUD_TOKEN }}
